# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/RobotRPiArduino

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/RobotRPiArduino

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/RobotRPiArduino/CMakeFiles /home/pi/RobotRPiArduino/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/RobotRPiArduino/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DisplayImage

# Build rule for target.
DisplayImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DisplayImage
.PHONY : DisplayImage

# fast build rule for target.
DisplayImage/fast:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/build
.PHONY : DisplayImage/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/main.cpp.s
.PHONY : main.cpp.s

src/DistanceSensor.o: src/DistanceSensor.cpp.o

.PHONY : src/DistanceSensor.o

# target to build an object file
src/DistanceSensor.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/DistanceSensor.cpp.o
.PHONY : src/DistanceSensor.cpp.o

src/DistanceSensor.i: src/DistanceSensor.cpp.i

.PHONY : src/DistanceSensor.i

# target to preprocess a source file
src/DistanceSensor.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/DistanceSensor.cpp.i
.PHONY : src/DistanceSensor.cpp.i

src/DistanceSensor.s: src/DistanceSensor.cpp.s

.PHONY : src/DistanceSensor.s

# target to generate assembly for a file
src/DistanceSensor.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/DistanceSensor.cpp.s
.PHONY : src/DistanceSensor.cpp.s

src/I2C.o: src/I2C.cpp.o

.PHONY : src/I2C.o

# target to build an object file
src/I2C.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/I2C.cpp.o
.PHONY : src/I2C.cpp.o

src/I2C.i: src/I2C.cpp.i

.PHONY : src/I2C.i

# target to preprocess a source file
src/I2C.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/I2C.cpp.i
.PHONY : src/I2C.cpp.i

src/I2C.s: src/I2C.cpp.s

.PHONY : src/I2C.s

# target to generate assembly for a file
src/I2C.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/I2C.cpp.s
.PHONY : src/I2C.cpp.s

src/Location.o: src/Location.cpp.o

.PHONY : src/Location.o

# target to build an object file
src/Location.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Location.cpp.o
.PHONY : src/Location.cpp.o

src/Location.i: src/Location.cpp.i

.PHONY : src/Location.i

# target to preprocess a source file
src/Location.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Location.cpp.i
.PHONY : src/Location.cpp.i

src/Location.s: src/Location.cpp.s

.PHONY : src/Location.s

# target to generate assembly for a file
src/Location.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Location.cpp.s
.PHONY : src/Location.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/Motor.o: src/Motor.cpp.o

.PHONY : src/Motor.o

# target to build an object file
src/Motor.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Motor.cpp.o
.PHONY : src/Motor.cpp.o

src/Motor.i: src/Motor.cpp.i

.PHONY : src/Motor.i

# target to preprocess a source file
src/Motor.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Motor.cpp.i
.PHONY : src/Motor.cpp.i

src/Motor.s: src/Motor.cpp.s

.PHONY : src/Motor.s

# target to generate assembly for a file
src/Motor.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Motor.cpp.s
.PHONY : src/Motor.cpp.s

src/Route.o: src/Route.cpp.o

.PHONY : src/Route.o

# target to build an object file
src/Route.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Route.cpp.o
.PHONY : src/Route.cpp.o

src/Route.i: src/Route.cpp.i

.PHONY : src/Route.i

# target to preprocess a source file
src/Route.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Route.cpp.i
.PHONY : src/Route.cpp.i

src/Route.s: src/Route.cpp.s

.PHONY : src/Route.s

# target to generate assembly for a file
src/Route.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Route.cpp.s
.PHONY : src/Route.cpp.s

src/Target.o: src/Target.cpp.o

.PHONY : src/Target.o

# target to build an object file
src/Target.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Target.cpp.o
.PHONY : src/Target.cpp.o

src/Target.i: src/Target.cpp.i

.PHONY : src/Target.i

# target to preprocess a source file
src/Target.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Target.cpp.i
.PHONY : src/Target.cpp.i

src/Target.s: src/Target.cpp.s

.PHONY : src/Target.s

# target to generate assembly for a file
src/Target.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/Target.cpp.s
.PHONY : src/Target.cpp.s

src/contouren.o: src/contouren.cpp.o

.PHONY : src/contouren.o

# target to build an object file
src/contouren.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/contouren.cpp.o
.PHONY : src/contouren.cpp.o

src/contouren.i: src/contouren.cpp.i

.PHONY : src/contouren.i

# target to preprocess a source file
src/contouren.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/contouren.cpp.i
.PHONY : src/contouren.cpp.i

src/contouren.s: src/contouren.cpp.s

.PHONY : src/contouren.s

# target to generate assembly for a file
src/contouren.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/contouren.cpp.s
.PHONY : src/contouren.cpp.s

src/draw.o: src/draw.cpp.o

.PHONY : src/draw.o

# target to build an object file
src/draw.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/draw.cpp.o
.PHONY : src/draw.cpp.o

src/draw.i: src/draw.cpp.i

.PHONY : src/draw.i

# target to preprocess a source file
src/draw.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/draw.cpp.i
.PHONY : src/draw.cpp.i

src/draw.s: src/draw.cpp.s

.PHONY : src/draw.s

# target to generate assembly for a file
src/draw.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/draw.cpp.s
.PHONY : src/draw.cpp.s

src/grouping.o: src/grouping.cpp.o

.PHONY : src/grouping.o

# target to build an object file
src/grouping.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/grouping.cpp.o
.PHONY : src/grouping.cpp.o

src/grouping.i: src/grouping.cpp.i

.PHONY : src/grouping.i

# target to preprocess a source file
src/grouping.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/grouping.cpp.i
.PHONY : src/grouping.cpp.i

src/grouping.s: src/grouping.cpp.s

.PHONY : src/grouping.s

# target to generate assembly for a file
src/grouping.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/grouping.cpp.s
.PHONY : src/grouping.cpp.s

src/image.o: src/image.cpp.o

.PHONY : src/image.o

# target to build an object file
src/image.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/image.cpp.o
.PHONY : src/image.cpp.o

src/image.i: src/image.cpp.i

.PHONY : src/image.i

# target to preprocess a source file
src/image.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/image.cpp.i
.PHONY : src/image.cpp.i

src/image.s: src/image.cpp.s

.PHONY : src/image.s

# target to generate assembly for a file
src/image.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/image.cpp.s
.PHONY : src/image.cpp.s

src/target_cv.o: src/target_cv.cpp.o

.PHONY : src/target_cv.o

# target to build an object file
src/target_cv.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/target_cv.cpp.o
.PHONY : src/target_cv.cpp.o

src/target_cv.i: src/target_cv.cpp.i

.PHONY : src/target_cv.i

# target to preprocess a source file
src/target_cv.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/target_cv.cpp.i
.PHONY : src/target_cv.cpp.i

src/target_cv.s: src/target_cv.cpp.s

.PHONY : src/target_cv.s

# target to generate assembly for a file
src/target_cv.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/src/target_cv.cpp.s
.PHONY : src/target_cv.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... DisplayImage"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/DistanceSensor.o"
	@echo "... src/DistanceSensor.i"
	@echo "... src/DistanceSensor.s"
	@echo "... src/I2C.o"
	@echo "... src/I2C.i"
	@echo "... src/I2C.s"
	@echo "... src/Location.o"
	@echo "... src/Location.i"
	@echo "... src/Location.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/Motor.o"
	@echo "... src/Motor.i"
	@echo "... src/Motor.s"
	@echo "... src/Route.o"
	@echo "... src/Route.i"
	@echo "... src/Route.s"
	@echo "... src/Target.o"
	@echo "... src/Target.i"
	@echo "... src/Target.s"
	@echo "... src/contouren.o"
	@echo "... src/contouren.i"
	@echo "... src/contouren.s"
	@echo "... src/draw.o"
	@echo "... src/draw.i"
	@echo "... src/draw.s"
	@echo "... src/grouping.o"
	@echo "... src/grouping.i"
	@echo "... src/grouping.s"
	@echo "... src/image.o"
	@echo "... src/image.i"
	@echo "... src/image.s"
	@echo "... src/target_cv.o"
	@echo "... src/target_cv.i"
	@echo "... src/target_cv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

